version: "3"

services:
  ltsm-web-service:
#    command: "tail -f /tmp/ltsm.log"
    build:
      context: ./docker/ltsm
      dockerfile: Dockerfile
    volumes:
      - ./docker/ltsm:/ltsm
      - /ltsm/.local
      - /ltsm/.pyenv
      - /ltsm/.cache
#    depends_on:
#      - ltsm-database
#    environment:
#     DB Credentials Here
#    ports:
#      - "XXXX:XXXX"
    networks:
      - ltsm-net
#  rework-database:
#    build:
#      context: ./docker/database
#      dockerfile: Dockerfile
#    volumes:
#      - ./ltsm_stock_market_prediction:/ltsm    ports:
#      - "XXXX:XXXX"
#    networks:
#      - ltsm-net
#    environment:
#     DB Credentials Here

networks:
  ltsm-net:
    driver: bridge